default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

development:
  <<: *default
  database: <%= ENV['DATABASE_URL'] || 'your_local_development_db_name' %>
  username: <%= ENV['DATABASE_USERNAME'] || 'your_local_username' %>
  password: <%= ENV['DATABASE_PASSWORD'] || 'your_local_password' %>
  host: <%= ENV['DATABASE_HOST'] || 'localhost' %>

test:
  <<: *default
  database: <%= ENV['DATABASE_URL'] || 'your_local_test_db_name' %>
  username: <%= ENV['DATABASE_USERNAME'] || 'your_local_username' %>
  password: <%= ENV['DATABASE_PASSWORD'] || 'your_local_password' %>
  host: <%= ENV['DATABASE_HOST'] || 'localhost' %>

production:
  primary:
    <<: *default
    database: <%= ENV['DATABASE_URL'] || 'your_production_db_name' %>
    username: <%= ENV['DATABASE_USERNAME'] || 'your_production_username' %>
    password: <%= ENV['DATABASE_PASSWORD'] || 'your_production_password' %>
    host: <%= ENV['DATABASE_HOST'] || 'your_production_host' %>
  cache:
    <<: *default
    database: <%= ENV['DATABASE_URL'] || 'your_production_cache_db_name' %>
    migrations_paths: db/cache_migrate
  queue:
    <<: *default
    database: <%= ENV['DATABASE_URL'] || 'your_production_queue_db_name' %>
    migrations_paths: db/queue_migrate
  cable:
    <<: *default
    database: <%= ENV['DATABASE_URL'] || 'your_production_cable_db_name' %>
    migrations_paths: db/cable_migrate
